ARG ROSDISTRO=noetic

FROM ros:$ROSDISTRO-robot

ARG ROSDISTRO

# Set environment variables
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

ENV TERM xterm-256color

# Tools
RUN apt-get update && apt-get install -y \
    zsh \
    ssh \
    git \
    curl \
    python3-pip \
    python3-flake8 \
    build-essential \
    cmake \
    iputils-ping 


RUN pip3 install -U --no-cache-dir\
    argcomplete \
    flake8-blind-except \
    flake8-builtins \
    flake8-class-newline \
    flake8-comprehensions \
    flake8-deprecated \
    flake8-return \
    flake8-length \
    flake8-todo \
    flake8-quotes \
    black \
    numpy \
    open3d \
    pyquaternion

# ROS
RUN apt-get update && apt-get install -y \
    pkg-config \
    python3-catkin-tools \
    python3-rosdep \
    python3-rosinstall-generator \
    python3-vcstool \
    ros-$ROSDISTRO-rqt \
    ros-$ROSDISTRO-rqt-action \
    ros-$ROSDISTRO-rqt-console \
    ros-$ROSDISTRO-rqt-service-caller \
    ros-$ROSDISTRO-rqt-graph \
    ros-$ROSDISTRO-rqt-topic \
    ros-$ROSDISTRO-rqt-top \
    ros-$ROSDISTRO-rqt-reconfigure \
    ros-$ROSDISTRO-rqt-joint-trajectory-controller \
    ros-$ROSDISTRO-rqt-tf-tree \
    ros-$ROSDISTRO-moveit \
    ros-$ROSDISTRO-trac-ik-kinematics-plugin \
    # UR dependencies
    ros-$ROSDISTRO-ur-client-library \
    ros-$ROSDISTRO-ur-msgs \
    ros-$ROSDISTRO-controller-manager \
    ros-$ROSDISTRO-pass-through-controllers \
    ros-$ROSDISTRO-force-torque-sensor-controller \
    ros-$ROSDISTRO-industrial-robot-status-interface \
    ros-$ROSDISTRO-industrial-robot-status-controller \
    ros-$ROSDISTRO-joint-state-controller \
    ros-$ROSDISTRO-joint-trajectory-controller \
    ros-$ROSDISTRO-cartesian-trajectory-controller \
    ros-$ROSDISTRO-scaled-joint-trajectory-controller \
    ros-$ROSDISTRO-speed-scaling-interface \
    ros-$ROSDISTRO-speed-scaling-state-controller \
    ros-$ROSDISTRO-velocity-controllers \
    ros-$ROSDISTRO-effort-controllers \
    ros-$ROSDISTRO-kdl-parser \
    # RQT joint trajectory plot
    ros-$ROSDISTRO-roslint \
    ros-$ROSDISTRO-rqt-gui \
    ros-$ROSDISTRO-rqt-gui-py \
    ros-$ROSDISTRO-rqt-py-common \
    python3-matplotlib \
    #STOMP
    ros-$ROSDISTRO-ros-industrial-cmake-boilerplate \
    # Realsense
    software-properties-common \
    ros-$ROS_DISTRO-rqt-image-view \
    ros-$ROS_DISTRO-ddynamic-reconfigure \
    ros-$ROS_DISTRO-rgbd-launch \
    # roslibpy
    ros-$ROS_DISTRO-rosbridge-suite 
    ## Foxglove
    # libnotify4 \
    # xdg-utils \
    # libappindicator3-1 

# Add repo and install realsense pkgs
RUN apt-key adv \
    --keyserver keyserver.ubuntu.com \
    --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || \
    apt-key adv \
    --keyserver hkp://keyserver.ubuntu.com:80 \
    --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE \
    && add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u \
    && apt-get install -y --install-recommends \
    librealsense2-dkms librealsense2-utils \
    librealsense2-dev librealsense2-dbg

# RUN mkdir foxglove
# WORKDIR /foxglove
# RUN  curl -LJO https://github.com/foxglove/studio/releases/download/v1.28.0/foxglove-studio-1.28.0-linux-amd64.deb \
#     &&  apt-get -y install ./foxglove-studio-*.deb \
#     && rm -r ./foxglove-studio-*.deb

# Reduce size by removing apt cache
RUN ["/bin/bash", "-c", "rm -rf /var/lib/apt/lists/*"]

# Add nice permision to container
RUN echo "* - nice -15" >> /etc/security/limits.conf

# build STOMP dependency nlot
RUN ["/bin/bash", "-c", "git clone https://github.com/stevengj/nlopt.git &&\
    cd nlopt &&\
    mkdir build &&\
    cd build &&\
    cmake .. &&\
    make &&\
    make install"]

# Create workspace
RUN mkdir -p dev_ws/src
WORKDIR /dev_ws/src

# Clone pkgs (STOMP, rqt_joint_trajectory, ros-realsense) into workspace
RUN ["/bin/bash", "-c", "git clone https://github.com/ros-industrial/stomp.git &&\
    git clone https://github.com/ros-industrial/stomp_ros.git &&\
    git clone https://github.com/tork-a/rqt_joint_trajectory_plot.git &&\
    git clone https://github.com/rjwb1/realsense-ros.git&&\
    git clone https://github.com/RobotWebTools/tf2_web_republisher.git"]


# Copy local pkg's from host to container
COPY . /dev_ws/src/

# Build catkin workspace
WORKDIR /dev_ws

RUN ["/bin/bash", "-c", "source /opt/ros/$ROSDISTRO/setup.bash &&\
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release &&\
    catkin build \
    "]

# Set shell to zsh
SHELL ["zsh", "chsh -s ~/.zshrc" ]

# Copy and make setup script executable
COPY .docker/setup.zsh /dev_ws/setup.zsh
RUN ["/bin/bash", "-c", " chmod 777 /dev_ws/setup.zsh"]

# Copy and make entrypoint script executable
RUN ["/bin/bash", "-c", "cp /dev_ws/src/.docker/entrypoint_zsh.sh / && chmod 777 /entrypoint_zsh.sh"]
ENTRYPOINT ["zsh", "/entrypoint_zsh.sh" ]

# start ZSH shell
CMD ["zsh"]